default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  timeout: 5000

development:
  <<: *default
  username: afeefa
  password: ThisIsAStrongPassword123!
  database: afeefa_development

test:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/test.sqlite3

production:
  <<: *default
  username: afeefa
  password: ThisIsAStrongPassword123!
  database: afeefa_production
