facebook:
  app_id: <%= ENV["FB_APP_ID"] %>
  app_secret: <%= ENV["FB_APP_SECRET"] %>
  api_token_for_event_request: MapCat_050615
  pages_for_events:
    montagscafedresden: 1680988942178044
    dresdenfueralle: 1568930816673620
geocoding:
  api_token: MapCat_050615
phraseapp:
  project_id: 473a16f79defb1cd2d47464deb4c6008
  api_token: 17f10e70ea0f09650b3d8d3a734554f907d4bfa661799adaca106fe47a45378b
  fallback_list: [en, de]
