afeefa:
  fapi_sync_active: true
  fapi_webhook_api_token: <%= ENV["FAPI_CHANGES_WEBHOOK_TOKEN"] %>
  fapi_url: https://afeefa.de/api
facebook:
  active: false
  app_id: <%= ENV["FB_APP_ID"] %>
  app_secret: <%= ENV["FB_APP_SECRET"] %>
  api_token_for_event_request: <%= ENV["FB_API_TOKEN"] %>
  log_file: log/facebook.log
  pages_for_events:
    afeefa: 1616918288526361
    montagscafedresden: 1680988942178044
    dresdenfueralle: 1568930816673620
    johannstaedterkulturtreff: 168294379862523
    golgipark: 473356176149010
    HELLERAU.FAN: 148383831850095
geocoding:
  api_token: <%= ENV["GEO_API_TOKEN"] %>
translations:
  api_token: <%= ENV["_API_TOKEN"] %>
phraseapp:
  active: true
  project_id: <%= ENV["PA_PROJECT_ID"] %>
  api_token: <%= ENV["PA_TOKEN"] %>
  webhook_api_token: <%= ENV["PA_WEBHOOK_API_TOKEN"] %>
  log_file: log/phraseapp.log
chapters_api_path: 'http://localhost:3010/chapters'
