facebook:
  active: false
  app_id: <%= ENV["FB_APP_ID"] %>
  app_secret: <%= ENV["FB_APP_SECRET"] %>
  api_token_for_event_request: <%= ENV["FB_API_TOKEN"] %>
  log_file: log/facebook.log
  pages_for_events:
    afeefa: 1616918288526361
    montagscafedresden: 1680988942178044
    dresdenfueralle: 1568930816673620
    johannstaedterkulturtreff: 168294379862523
    golgipark: 473356176149010
    HELLERAU.FAN: 148383831850095
geocoding:
  api_token: <%= ENV["GEO_API_TOKEN"] %>
translations:
  api_token: <%= ENV["_API_TOKEN"] %>
phraseapp:
  active: false
  project_id: <%= ENV["PA_LIVE_PROJECT_ID"] %>
  api_token: <%= ENV["PA_WRITE_TOKEN"] %>
  fallback_list: [en, de]
  dev_project_id: <%= ENV["PA_DEV_PROJECT_ID"] %>
  test_project_id: <%= ENV["PA_TEST_PROJECT_ID"] %>
  log_file: log/phraseapp.log
migration:
  phraseapp:
    project_id: <%= ENV["PA_LEGACY_LIVE_PROJECT_ID"] %>
    api_token: <%= ENV["PA_READ_TOKEN"] %>
