<?php
$languages = ['arabic', 'english', 'french', 'german', 'kurdish', 'persian', 'russian', 'serbian', 'tigrinya', 'urdu'];

foreach($languages as $lang) {
  $oldData = json_decode( mb_convert_encoding(file_get_contents('input/' . $lang . '.json'), 'UTF-8') );
  $newData = new stdClass();
  // var_dump($oldData);
  // die();
  
  foreach(getNavigationItems() as $nav) {
    $oldProp = 'cat.' . $nav['legacy_title'];
    $newProp = "navigation_item." . $nav['id'] . ".title";
    if( property_exists($oldData, $oldProp) ) {
      // array_push($newData, array("navigation_item." . $nav['id'] . ".title" => $oldData->$prop) );
      $newData->$newProp = $oldData->$oldProp;
    }
  }
  // $json = json_encode($newData, JSON_PRETTY_PRINT);
  $json = json_encode($newData, JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT);
  // var_dump($json);
  file_put_contents('output/navigation-' . $lang . '.json', $json, LOCK_EX);
}

function getNavigationItems(){
  return array(
    array(
      "area" => "bautzen",
      "id" => 21,
      "legacy_title" => "general",
      "title" => "Allgemeines",
      "color" => "#999999",
      "icon" => "general",
      "parent_id" => NULL,
    ),
    array(
      "area" => "bautzen",
      "id" => 22,
      "legacy_title" => "wifi",
      "title" => "Kostenloses WLAN",
      "color" => NULL,
      "icon" => "wifi",
      "parent_id" => 21,
    ),
    array(
      "area" => "bautzen",
      "id" => 23,
      "legacy_title" => "jewish",
      "title" => "Jüdische Gemeinschaft",
      "color" => NULL,
      "icon" => "jewish",
      "parent_id" => 21,
    ),
    array(
      "area" => "bautzen",
      "id" => 24,
      "legacy_title" => "christian",
      "title" => "Christliche Gemeinschaft",
      "color" => NULL,
      "icon" => "christian",
      "parent_id" => 21,
    ),
    array(
      "area" => "bautzen",
      "id" => 25,
      "legacy_title" => "islam",
      "title" => "Islamische Gemeinschaft",
      "color" => NULL,
      "icon" => "islam",
      "parent_id" => 21,
    ),
    array(
      "area" => "bautzen",
      "id" => 26,
      "legacy_title" => "religious-other",
      "title" => "Religiöse Einrichtung",
      "color" => NULL,
      "icon" => "religious-other",
      "parent_id" => 21,
    ),
    array(
      "area" => "bautzen",
      "id" => 27,
      "legacy_title" => "shop",
      "title" => "Interkultureller Einkaufsladen",
      "color" => NULL,
      "icon" => "shop",
      "parent_id" => 21,
    ),
    array(
      "area" => "bautzen",
      "id" => 28,
      "legacy_title" => "nature",
      "title" => "Parks + Gärten",
      "color" => NULL,
      "icon" => "nature",
      "parent_id" => 21,
    ),
    array(
      "area" => "bautzen",
      "id" => 29,
      "legacy_title" => "authority",
      "title" => "Behörden",
      "color" => NULL,
      "icon" => "authority",
      "parent_id" => 21,
    ),
    array(
      "area" => "bautzen",
      "id" => 30,
      "legacy_title" => "hospital",
      "title" => "Krankenhaus",
      "color" => NULL,
      "icon" => "hospital",
      "parent_id" => 21,
    ),
    array(
      "area" => "bautzen",
      "id" => 31,
      "legacy_title" => "police",
      "title" => "Polizei",
      "color" => NULL,
      "icon" => "police",
      "parent_id" => 21,
    ),
    array(
      "area" => "bautzen",
      "id" => 32,
      "legacy_title" => "public-transport",
      "title" => "Haltestelle",
      "color" => NULL,
      "icon" => "public-transport",
      "parent_id" => 21,
    ),
    array(
      "area" => "bautzen",
      "id" => 33,
      "legacy_title" => "swimming",
      "title" => "Schwimmen",
      "color" => NULL,
      "icon" => NULL,
      "parent_id" => 21,
    ),
    array(
      "area" => "bautzen",
      "id" => 34,
      "legacy_title" => "language",
      "title" => "Sprache",
      "color" => "#E4B100",
      "icon" => "language",
      "parent_id" => NULL,
    ),
    array(
      "area" => "bautzen",
      "id" => 35,
      "legacy_title" => "german-course",
      "title" => "freier Deutschkurs",
      "color" => NULL,
      "icon" => "german-course",
      "parent_id" => 34,
    ),
    array(
      "area" => "bautzen",
      "id" => 36,
      "legacy_title" => "german-course-state",
      "title" => "staatlicher Deutschkurs",
      "color" => NULL,
      "icon" => "german-course-state",
      "parent_id" => 34,
    ),
    array(
      "area" => "bautzen",
      "id" => 37,
      "legacy_title" => "meet-and-speak",
      "title" => "Sprachtreff",
      "color" => NULL,
      "icon" => "meet-and-speak",
      "parent_id" => 34,
    ),
    array(
      "area" => "bautzen",
      "id" => 38,
      "legacy_title" => "learning-place",
      "title" => "Lernort",
      "color" => NULL,
      "icon" => "learning-place",
      "parent_id" => 34,
    ),
    array(
      "area" => "bautzen",
      "id" => 39,
      "legacy_title" => "interpreter",
      "title" => "Übersetzer/ Dolmetscher",
      "color" => NULL,
      "icon" => "interpreter",
      "parent_id" => 34,
    ),
    array(
      "area" => "bautzen",
      "id" => 40,
      "legacy_title" => "foreign-language",
      "title" => "Fremdsprachen",
      "color" => NULL,
      "icon" => "foreign-language",
      "parent_id" => 34,
    ),
    array(
      "area" => "bautzen",
      "id" => 41,
      "legacy_title" => "medic",
      "title" => "Gesundheit",
      "color" => "#A21C15",
      "icon" => "medic",
      "parent_id" => NULL,
    ),
    array(
      "area" => "bautzen",
      "id" => 42,
      "legacy_title" => "medical-counselling",
      "title" => "Medizinische Beratung",
      "color" => NULL,
      "icon" => "medical-counselling",
      "parent_id" => 41,
    ),
    array(
      "area" => "bautzen",
      "id" => 43,
      "legacy_title" => "psychological-counselling",
      "title" => "Psychologische Beratung",
      "color" => NULL,
      "icon" => "psychological-counselling",
      "parent_id" => 41,
    ),
    array(
      "area" => "bautzen",
      "id" => 44,
      "legacy_title" => "jobs",
      "title" => "Arbeit + Bildung",
      "color" => "#085272",
      "icon" => "jobs",
      "parent_id" => NULL,
    ),
    array(
      "area" => "bautzen",
      "id" => 45,
      "legacy_title" => "job-counselling",
      "title" => "Berufsberatung",
      "color" => NULL,
      "icon" => "job-counselling",
      "parent_id" => 44,
    ),
    array(
      "area" => "bautzen",
      "id" => 46,
      "legacy_title" => "education-counselling",
      "title" => "Bildungsberatung",
      "color" => NULL,
      "icon" => "education-counselling",
      "parent_id" => 44,
    ),
    array(
      "area" => "bautzen",
      "id" => 47,
      "legacy_title" => "political-education",
      "title" => "Politische Bildung",
      "color" => NULL,
      "icon" => "political-education",
      "parent_id" => 44,
    ),
    array(
      "area" => "bautzen",
      "id" => 48,
      "legacy_title" => "library",
      "title" => "Bibliothek",
      "color" => NULL,
      "icon" => "library",
      "parent_id" => 44,
    ),
    array(
      "area" => "bautzen",
      "id" => 49,
      "legacy_title" => "consultation",
      "title" => "Beratung",
      "color" => "#5E6823",
      "icon" => "consultation",
      "parent_id" => NULL,
    ),
    array(
      "area" => "bautzen",
      "id" => 50,
      "legacy_title" => "asylum-counselling",
      "title" => "Migrationsberatung",
      "color" => NULL,
      "icon" => "asylum-counselling",
      "parent_id" => 49,
    ),
    array(
      "area" => "bautzen",
      "id" => 51,
      "legacy_title" => "legal-advice",
      "title" => "Rechtsberatung",
      "color" => NULL,
      "icon" => "legal-advice",
      "parent_id" => 49,
    ),
    array(
      "area" => "bautzen",
      "id" => 52,
      "legacy_title" => "social-counselling",
      "title" => "Sozialberatung",
      "color" => NULL,
      "icon" => "social-counselling",
      "parent_id" => 49,
    ),
    array(
      "area" => "bautzen",
      "id" => 53,
      "legacy_title" => "family-counselling",
      "title" => "Familienberatung",
      "color" => NULL,
      "icon" => "family-counselling",
      "parent_id" => 49,
    ),
    array(
      "area" => "bautzen",
      "id" => 54,
      "legacy_title" => "volunteer-coordination",
      "title" => "Ehrenamtskoordination",
      "color" => NULL,
      "icon" => "volunteer-coordination",
      "parent_id" => 49,
    ),
    array(
      "area" => "bautzen",
      "id" => 55,
      "legacy_title" => "leisure",
      "title" => "Freizeit",
      "color" => "#318B86",
      "icon" => "leisure",
      "parent_id" => NULL,
    ),
    array(
      "area" => "bautzen",
      "id" => 56,
      "legacy_title" => "sports",
      "title" => "Sport",
      "color" => NULL,
      "icon" => "sports",
      "parent_id" => 55,
    ),
    array(
      "area" => "bautzen",
      "id" => 57,
      "legacy_title" => "museum",
      "title" => "Museum",
      "color" => NULL,
      "icon" => "museum",
      "parent_id" => 55,
    ),
    array(
      "area" => "bautzen",
      "id" => 58,
      "legacy_title" => "music",
      "title" => "Musik",
      "color" => NULL,
      "icon" => "music",
      "parent_id" => 55,
    ),
    array(
      "area" => "bautzen",
      "id" => 59,
      "legacy_title" => "stage",
      "title" => "Bühne",
      "color" => NULL,
      "icon" => "stage",
      "parent_id" => 55,
    ),
    array(
      "area" => "bautzen",
      "id" => 60,
      "legacy_title" => "craft-art",
      "title" => "Handwerk + Kunst",
      "color" => NULL,
      "icon" => "craft-art",
      "parent_id" => 55,
    ),
    array(
      "area" => "bautzen",
      "id" => 61,
      "legacy_title" => "workspace",
      "title" => "Räume + Werkstätten",
      "color" => NULL,
      "icon" => "workspace",
      "parent_id" => 55,
    ),
    array(
      "area" => "bautzen",
      "id" => 62,
      "legacy_title" => "gardening",
      "title" => "Garten",
      "color" => NULL,
      "icon" => "gardening",
      "parent_id" => 55,
    ),
    array(
      "area" => "bautzen",
      "id" => 63,
      "legacy_title" => "cooking",
      "title" => "Kochen",
      "color" => NULL,
      "icon" => "cooking",
      "parent_id" => 55,
    ),
    array(
      "area" => "bautzen",
      "id" => 64,
      "legacy_title" => "festival",
      "title" => "Fest",
      "color" => NULL,
      "icon" => "festival",
      "parent_id" => 55,
    ),
    array(
      "area" => "bautzen",
      "id" => 65,
      "legacy_title" => "lecture",
      "title" => "Vortrag",
      "color" => NULL,
      "icon" => "lecture",
      "parent_id" => 55,
    ),
    array(
      "area" => "bautzen",
      "id" => 66,
      "legacy_title" => "film",
      "title" => "Film",
      "color" => NULL,
      "icon" => "film",
      "parent_id" => 55,
    ),
    array(
      "area" => "bautzen",
      "id" => 67,
      "legacy_title" => "congress",
      "title" => "Kongresse + Messen",
      "color" => NULL,
      "icon" => "congress",
      "parent_id" => 55,
    ),
    array(
      "area" => "bautzen",
      "id" => 68,
      "legacy_title" => "community",
      "title" => "Gemeinschaft",
      "color" => "#693E75",
      "icon" => "community",
      "parent_id" => NULL,
    ),
    array(
      "area" => "bautzen",
      "id" => 69,
      "legacy_title" => "welcome-network",
      "title" => "Willkommensbündnis",
      "color" => NULL,
      "icon" => "welcome-network",
      "parent_id" => 68,
    ),
    array(
      "area" => "bautzen",
      "id" => 70,
      "legacy_title" => "meeting-place",
      "title" => "Treffpunkt",
      "color" => NULL,
      "icon" => "meeting-place",
      "parent_id" => 68,
    ),
    array(
      "area" => "bautzen",
      "id" => 71,
      "legacy_title" => "youth-club",
      "title" => "Jugendtreff",
      "color" => NULL,
      "icon" => "youth-club",
      "parent_id" => 68,
    ),
    array(
      "area" => "bautzen",
      "id" => 72,
      "legacy_title" => "childcare",
      "title" => "Kinderbetreuung",
      "color" => NULL,
      "icon" => "childcare",
      "parent_id" => 68,
    ),
    array(
      "area" => "bautzen",
      "id" => 73,
      "legacy_title" => "workshop",
      "title" => "Workshop",
      "color" => NULL,
      "icon" => "workshop",
      "parent_id" => 68,
    ),
    array(
      "area" => "bautzen",
      "id" => 74,
      "legacy_title" => "sponsorship",
      "title" => "Patenschaften",
      "color" => NULL,
      "icon" => "sponsorship",
      "parent_id" => 68,
    ),
    array(
      "area" => "bautzen",
      "id" => 75,
      "legacy_title" => "lgbt",
      "title" => "LGBT",
      "color" => NULL,
      "icon" => "lgbt",
      "parent_id" => 68,
    ),
    array(
      "area" => "bautzen",
      "id" => 76,
      "legacy_title" => "housing-project",
      "title" => "Wohnprojekte",
      "color" => NULL,
      "icon" => "housing-project",
      "parent_id" => 68,
    ),
    array(
      "area" => "bautzen",
      "id" => 77,
      "legacy_title" => "donation",
      "title" => "Spenden",
      "color" => "#CA7311",
      "icon" => "donation",
      "parent_id" => NULL,
    ),
    array(
      "area" => "bautzen",
      "id" => 78,
      "legacy_title" => "food",
      "title" => "Lebensmittel",
      "color" => NULL,
      "icon" => "food",
      "parent_id" => 77,
    ),
    array(
      "area" => "bautzen",
      "id" => 79,
      "legacy_title" => "clothes",
      "title" => "Kleidung",
      "color" => NULL,
      "icon" => "clothes",
      "parent_id" => 77,
    ),
    array(
      "area" => "bautzen",
      "id" => 80,
      "legacy_title" => "furniture",
      "title" => "Möbel",
      "color" => NULL,
      "icon" => "furniture",
      "parent_id" => 77,
    ),
    array(
      "area" => "bautzen",
      "id" => 81,
      "legacy_title" => "external-event",
      "title" => "integrierte Daten",
      "color" => NULL,
      "icon" => "external-event",
      "parent_id" => NULL,
    ),
    array(
      "area" => "bautzen",
      "id" => 82,
      "legacy_title" => "fb-event",
      "title" => "facebook Event",
      "color" => NULL,
      "icon" => "fb-event",
      "parent_id" => 81,
    ),
    array(
      "area" => "dresden",
      "id" => 83,
      "legacy_title" => "general",
      "title" => "Allgemeines",
      "color" => "#999999",
      "icon" => "general",
      "parent_id" => NULL,
    ),
    array(
      "area" => "dresden",
      "id" => 84,
      "legacy_title" => "wifi",
      "title" => "Kostenloses WLAN",
      "color" => NULL,
      "icon" => "wifi",
      "parent_id" => 83,
    ),
    array(
      "area" => "dresden",
      "id" => 85,
      "legacy_title" => "jewish",
      "title" => "Jüdische Gemeinschaft",
      "color" => NULL,
      "icon" => "jewish",
      "parent_id" => 83,
    ),
    array(
      "area" => "dresden",
      "id" => 86,
      "legacy_title" => "christian",
      "title" => "Christliche Gemeinschaft",
      "color" => NULL,
      "icon" => "christian",
      "parent_id" => 83,
    ),
    array(
      "area" => "dresden",
      "id" => 87,
      "legacy_title" => "islam",
      "title" => "Islamische Gemeinschaft",
      "color" => NULL,
      "icon" => "islam",
      "parent_id" => 83,
    ),
    array(
      "area" => "dresden",
      "id" => 88,
      "legacy_title" => "religious-other",
      "title" => "Religiöse Einrichtung",
      "color" => NULL,
      "icon" => "religious-other",
      "parent_id" => 83,
    ),
    array(
      "area" => "dresden",
      "id" => 89,
      "legacy_title" => "shop",
      "title" => "Interkultureller Einkaufsladen",
      "color" => NULL,
      "icon" => "shop",
      "parent_id" => 83,
    ),
    array(
      "area" => "dresden",
      "id" => 90,
      "legacy_title" => "nature",
      "title" => "Parks + Gärten",
      "color" => NULL,
      "icon" => "nature",
      "parent_id" => 83,
    ),
    array(
      "area" => "dresden",
      "id" => 91,
      "legacy_title" => "authority",
      "title" => "Behörden",
      "color" => NULL,
      "icon" => "authority",
      "parent_id" => 83,
    ),
    array(
      "area" => "dresden",
      "id" => 92,
      "legacy_title" => "hospital",
      "title" => "Krankenhaus",
      "color" => NULL,
      "icon" => "hospital",
      "parent_id" => 83,
    ),
    array(
      "area" => "dresden",
      "id" => 93,
      "legacy_title" => "police",
      "title" => "Polizei",
      "color" => NULL,
      "icon" => "police",
      "parent_id" => 83,
    ),
    array(
      "area" => "dresden",
      "id" => 94,
      "legacy_title" => "public-transport",
      "title" => "Haltestelle",
      "color" => NULL,
      "icon" => "public-transport",
      "parent_id" => 83,
    ),
    array(
      "area" => "dresden",
      "id" => 95,
      "legacy_title" => "language",
      "title" => "Sprache",
      "color" => "#E4B100",
      "icon" => "language",
      "parent_id" => NULL,
    ),
    array(
      "area" => "dresden",
      "id" => 96,
      "legacy_title" => "german-course",
      "title" => "freier Deutschkurs",
      "color" => NULL,
      "icon" => "german-course",
      "parent_id" => 95,
    ),
    array(
      "area" => "dresden",
      "id" => 97,
      "legacy_title" => "german-course-state",
      "title" => "staatlicher Deutschkurs",
      "color" => NULL,
      "icon" => "german-course-state",
      "parent_id" => 95,
    ),
    array(
      "area" => "dresden",
      "id" => 98,
      "legacy_title" => "meet-and-speak",
      "title" => "Sprachtreff",
      "color" => NULL,
      "icon" => "meet-and-speak",
      "parent_id" => 95,
    ),
    array(
      "area" => "dresden",
      "id" => 99,
      "legacy_title" => "learning-place",
      "title" => "Lernort",
      "color" => NULL,
      "icon" => "learning-place",
      "parent_id" => 95,
    ),
    array(
      "area" => "dresden",
      "id" => 100,
      "legacy_title" => "interpreter",
      "title" => "Übersetzer/ Dolmetscher",
      "color" => NULL,
      "icon" => "interpreter",
      "parent_id" => 95,
    ),
    array(
      "area" => "dresden",
      "id" => 101,
      "legacy_title" => "foreign-language",
      "title" => "Fremdsprachen",
      "color" => NULL,
      "icon" => "foreign-language",
      "parent_id" => 95,
    ),
    array(
      "area" => "dresden",
      "id" => 102,
      "legacy_title" => "medic",
      "title" => "Gesundheit",
      "color" => "#A21C15",
      "icon" => "medic",
      "parent_id" => NULL,
    ),
    array(
      "area" => "dresden",
      "id" => 103,
      "legacy_title" => "medical-counselling",
      "title" => "Medizinische Beratung",
      "color" => NULL,
      "icon" => "medical-counselling",
      "parent_id" => 102,
    ),
    array(
      "area" => "dresden",
      "id" => 104,
      "legacy_title" => "psychological-counselling",
      "title" => "Psychologische Beratung",
      "color" => NULL,
      "icon" => "psychological-counselling",
      "parent_id" => 102,
    ),
    array(
      "area" => "dresden",
      "id" => 105,
      "legacy_title" => "jobs",
      "title" => "Arbeit + Bildung",
      "color" => "#085272",
      "icon" => "jobs",
      "parent_id" => NULL,
    ),
    array(
      "area" => "dresden",
      "id" => 106,
      "legacy_title" => "job-counselling",
      "title" => "Berufsberatung",
      "color" => NULL,
      "icon" => "job-counselling",
      "parent_id" => 105,
    ),
    array(
      "area" => "dresden",
      "id" => 107,
      "legacy_title" => "education-counselling",
      "title" => "Bildungsberatung",
      "color" => NULL,
      "icon" => "education-counselling",
      "parent_id" => 105,
    ),
    array(
      "area" => "dresden",
      "id" => 108,
      "legacy_title" => "political-education",
      "title" => "Politische Bildung",
      "color" => NULL,
      "icon" => "political-education",
      "parent_id" => 105,
    ),
    array(
      "area" => "dresden",
      "id" => 109,
      "legacy_title" => "library",
      "title" => "Bibliothek",
      "color" => NULL,
      "icon" => "library",
      "parent_id" => 105,
    ),
    array(
      "area" => "dresden",
      "id" => 110,
      "legacy_title" => "consultation",
      "title" => "Beratung",
      "color" => "#5E6823",
      "icon" => "consultation",
      "parent_id" => NULL,
    ),
    array(
      "area" => "dresden",
      "id" => 111,
      "legacy_title" => "asylum-counselling",
      "title" => "Migrationsberatung",
      "color" => NULL,
      "icon" => "asylum-counselling",
      "parent_id" => 110,
    ),
    array(
      "area" => "dresden",
      "id" => 112,
      "legacy_title" => "legal-advice",
      "title" => "Rechtsberatung",
      "color" => NULL,
      "icon" => "legal-advice",
      "parent_id" => 110,
    ),
    array(
      "area" => "dresden",
      "id" => 113,
      "legacy_title" => "social-counselling",
      "title" => "Sozialberatung",
      "color" => NULL,
      "icon" => "social-counselling",
      "parent_id" => 110,
    ),
    array(
      "area" => "dresden",
      "id" => 114,
      "legacy_title" => "family-counselling",
      "title" => "Familienberatung",
      "color" => NULL,
      "icon" => "family-counselling",
      "parent_id" => 110,
    ),
    array(
      "area" => "dresden",
      "id" => 115,
      "legacy_title" => "volunteer-coordination",
      "title" => "Ehrenamtskoordination",
      "color" => NULL,
      "icon" => "volunteer-coordination",
      "parent_id" => 110,
    ),
    array(
      "area" => "dresden",
      "id" => 116,
      "legacy_title" => "leisure",
      "title" => "Freizeit",
      "color" => "#318B86",
      "icon" => "leisure",
      "parent_id" => NULL,
    ),
    array(
      "area" => "dresden",
      "id" => 117,
      "legacy_title" => "sports",
      "title" => "Sport",
      "color" => NULL,
      "icon" => "sports",
      "parent_id" => 116,
    ),
    array(
      "area" => "dresden",
      "id" => 118,
      "legacy_title" => "museum",
      "title" => "Museum",
      "color" => NULL,
      "icon" => "museum",
      "parent_id" => 116,
    ),
    array(
      "area" => "dresden",
      "id" => 119,
      "legacy_title" => "music",
      "title" => "Musik",
      "color" => NULL,
      "icon" => "music",
      "parent_id" => 116,
    ),
    array(
      "area" => "dresden",
      "id" => 120,
      "legacy_title" => "stage",
      "title" => "Bühne",
      "color" => NULL,
      "icon" => "stage",
      "parent_id" => 116,
    ),
    array(
      "area" => "dresden",
      "id" => 121,
      "legacy_title" => "craft-art",
      "title" => "Handwerk + Kunst",
      "color" => NULL,
      "icon" => "craft-art",
      "parent_id" => 116,
    ),
    array(
      "area" => "dresden",
      "id" => 122,
      "legacy_title" => "workspace",
      "title" => "Räume + Werkstätten",
      "color" => NULL,
      "icon" => "workspace",
      "parent_id" => 116,
    ),
    array(
      "area" => "dresden",
      "id" => 123,
      "legacy_title" => "gardening",
      "title" => "Garten",
      "color" => NULL,
      "icon" => "gardening",
      "parent_id" => 116,
    ),
    array(
      "area" => "dresden",
      "id" => 124,
      "legacy_title" => "cooking",
      "title" => "Kochen",
      "color" => NULL,
      "icon" => "cooking",
      "parent_id" => 116,
    ),
    array(
      "area" => "dresden",
      "id" => 125,
      "legacy_title" => "festival",
      "title" => "Fest",
      "color" => NULL,
      "icon" => "festival",
      "parent_id" => 116,
    ),
    array(
      "area" => "dresden",
      "id" => 126,
      "legacy_title" => "lecture",
      "title" => "Vortrag",
      "color" => NULL,
      "icon" => "lecture",
      "parent_id" => 116,
    ),
    array(
      "area" => "dresden",
      "id" => 127,
      "legacy_title" => "film",
      "title" => "Film",
      "color" => NULL,
      "icon" => "film",
      "parent_id" => 116,
    ),
    array(
      "area" => "dresden",
      "id" => 128,
      "legacy_title" => "congress",
      "title" => "Kongresse + Messen",
      "color" => NULL,
      "icon" => "congress",
      "parent_id" => 116,
    ),
    array(
      "area" => "dresden",
      "id" => 129,
      "legacy_title" => "community",
      "title" => "Gemeinschaft",
      "color" => "#693E75",
      "icon" => "community",
      "parent_id" => NULL,
    ),
    array(
      "area" => "dresden",
      "id" => 130,
      "legacy_title" => "welcome-network",
      "title" => "Willkommensbündnis",
      "color" => NULL,
      "icon" => "welcome-network",
      "parent_id" => 129,
    ),
    array(
      "area" => "dresden",
      "id" => 131,
      "legacy_title" => "meeting-place",
      "title" => "Treffpunkt",
      "color" => NULL,
      "icon" => "meeting-place",
      "parent_id" => 129,
    ),
    array(
      "area" => "dresden",
      "id" => 132,
      "legacy_title" => "youth-club",
      "title" => "Jugendtreff",
      "color" => NULL,
      "icon" => "youth-club",
      "parent_id" => 129,
    ),
    array(
      "area" => "dresden",
      "id" => 133,
      "legacy_title" => "childcare",
      "title" => "Kinderbetreuung",
      "color" => NULL,
      "icon" => "childcare",
      "parent_id" => 129,
    ),
    array(
      "area" => "dresden",
      "id" => 134,
      "legacy_title" => "workshop",
      "title" => "Workshop",
      "color" => NULL,
      "icon" => "workshop",
      "parent_id" => 129,
    ),
    array(
      "area" => "dresden",
      "id" => 135,
      "legacy_title" => "sponsorship",
      "title" => "Patenschaften",
      "color" => NULL,
      "icon" => "sponsorship",
      "parent_id" => 129,
    ),
    array(
      "area" => "dresden",
      "id" => 136,
      "legacy_title" => "lgbt",
      "title" => "LGBT",
      "color" => NULL,
      "icon" => "lgbt",
      "parent_id" => 129,
    ),
    array(
      "area" => "dresden",
      "id" => 137,
      "legacy_title" => "housing-project",
      "title" => "Wohnprojekte",
      "color" => NULL,
      "icon" => "housing-project",
      "parent_id" => 129,
    ),
    array(
      "area" => "dresden",
      "id" => 138,
      "legacy_title" => "donation",
      "title" => "Spenden",
      "color" => "#CA7311",
      "icon" => "donation",
      "parent_id" => NULL,
    ),
    array(
      "area" => "dresden",
      "id" => 139,
      "legacy_title" => "food",
      "title" => "Lebensmittel",
      "color" => NULL,
      "icon" => "food",
      "parent_id" => 138,
    ),
    array(
      "area" => "dresden",
      "id" => 140,
      "legacy_title" => "clothes",
      "title" => "Kleidung",
      "color" => NULL,
      "icon" => "clothes",
      "parent_id" => 138,
    ),
    array(
      "area" => "dresden",
      "id" => 141,
      "legacy_title" => "furniture",
      "title" => "Möbel",
      "color" => NULL,
      "icon" => "furniture",
      "parent_id" => 138,
    ),
    array(
      "area" => "dresden",
      "id" => 142,
      "legacy_title" => "external-event",
      "title" => "integrierte Daten",
      "color" => NULL,
      "icon" => "external-event",
      "parent_id" => NULL,
    ),
    array(
      "area" => "dresden",
      "id" => 143,
      "legacy_title" => "fb-event",
      "title" => "facebook Event",
      "color" => NULL,
      "icon" => "fb-event",
      "parent_id" => 142,
    ),
    array(
      "area" => "leipzig",
      "id" => 1,
      "legacy_title" => "hotspots",
      "title" => "Hot Spots",
      "color" => NULL,
      "icon" => "hotspots",
      "parent_id" => NULL,
    ),
    array(
      "area" => "leipzig",
      "id" => 2,
      "legacy_title" => "work-and-education",
      "title" => "Bildung + Arbeit",
      "color" => "#085272",
      "icon" => "work-and-education",
      "parent_id" => NULL,
    ),
    array(
      "area" => "leipzig",
      "id" => 3,
      "legacy_title" => "learning-german",
      "title" => "Deutsch lernen",
      "color" => NULL,
      "icon" => NULL,
      "parent_id" => 2,
    ),
    array(
      "area" => "leipzig",
      "id" => 4,
      "legacy_title" => "kita-and-school",
      "title" => "Kindergarten und Schule",
      "color" => NULL,
      "icon" => NULL,
      "parent_id" => 2,
    ),
    array(
      "area" => "leipzig",
      "id" => 5,
      "legacy_title" => "work-learn-study",
      "title" => "Arbeit, Ausbildung, Studium",
      "color" => NULL,
      "icon" => NULL,
      "parent_id" => 2,
    ),
    array(
      "area" => "leipzig",
      "id" => 6,
      "legacy_title" => "living-in-leipzig",
      "title" => "Leben in Leipzig",
      "color" => "#E4B100",
      "icon" => "living-in-leipzig",
      "parent_id" => NULL,
    ),
    array(
      "area" => "leipzig",
      "id" => 7,
      "legacy_title" => "mobility",
      "title" => "Mobil sein",
      "color" => NULL,
      "icon" => NULL,
      "parent_id" => 6,
    ),
    array(
      "area" => "leipzig",
      "id" => 8,
      "legacy_title" => "religion",
      "title" => "Religion",
      "color" => NULL,
      "icon" => NULL,
      "parent_id" => 6,
    ),
    array(
      "area" => "leipzig",
      "id" => 9,
      "legacy_title" => "housing",
      "title" => "Wohnen",
      "color" => NULL,
      "icon" => NULL,
      "parent_id" => 6,
    ),
    array(
      "area" => "leipzig",
      "id" => 10,
      "legacy_title" => "health",
      "title" => "Gesundheit",
      "color" => NULL,
      "icon" => NULL,
      "parent_id" => 6,
    ),
    array(
      "area" => "leipzig",
      "id" => 11,
      "legacy_title" => "leisure",
      "title" => "Freizeit",
      "color" => NULL,
      "icon" => "leisure",
      "parent_id" => 6,
    ),
    array(
      "area" => "leipzig",
      "id" => 12,
      "legacy_title" => "daily-life",
      "title" => "Alltag",
      "color" => NULL,
      "icon" => NULL,
      "parent_id" => 6,
    ),
    array(
      "area" => "leipzig",
      "id" => 13,
      "legacy_title" => "participate",
      "title" => "Mitwirken und sich einmischen",
      "color" => NULL,
      "icon" => NULL,
      "parent_id" => 6,
    ),
    array(
      "area" => "leipzig",
      "id" => 14,
      "legacy_title" => "advice-and-support",
      "title" => "Rat und Begleitung",
      "color" => "#5E6823",
      "icon" => "advice-and-support",
      "parent_id" => NULL,
    ),
    array(
      "area" => "leipzig",
      "id" => 15,
      "legacy_title" => "family",
      "title" => "Kinder, Familie & Co",
      "color" => NULL,
      "icon" => NULL,
      "parent_id" => 14,
    ),
    array(
      "area" => "leipzig",
      "id" => 16,
      "legacy_title" => "social-advice",
      "title" => "Sozialberatung",
      "color" => NULL,
      "icon" => NULL,
      "parent_id" => 14,
    ),
    array(
      "area" => "leipzig",
      "id" => 17,
      "legacy_title" => "legal-advice",
      "title" => "Rechtsberatung",
      "color" => NULL,
      "icon" => "legal-advice",
      "parent_id" => 14,
    ),
    array(
      "area" => "leipzig",
      "id" => 18,
      "legacy_title" => "buddy-programme",
      "title" => "Patenschaften",
      "color" => NULL,
      "icon" => NULL,
      "parent_id" => 14,
    ),
    array(
      "area" => "leipzig",
      "id" => 19,
      "legacy_title" => "external-event",
      "title" => "integrierte Daten",
      "color" => NULL,
      "icon" => "external-event",
      "parent_id" => NULL,
    ),
    array(
      "area" => "leipzig",
      "id" => 20,
      "legacy_title" => "fb-event",
      "title" => "facebook Event",
      "color" => NULL,
      "icon" => "fb-event",
      "parent_id" => 19,
    ),
  );
}
?>