FactoryGirl.define do

  factory :facet, class: DataPlugins::Facet::Facet do
    title 'facet generated by factory'

    transient do
      owner_types []
    end

    after(:build) do |facet, evaluator|
      facet.owner_types = evaluator.owner_types.map do |owner_type|
        DataPlugins::Facet::FacetOwnerType.new(owner_type: owner_type)
      end
    end

    factory :facet_with_items do
      transient do
        facet_items_count 2
      end
      after(:create) do |facet, evaluator|
        create_list(:facet_item, evaluator.facet_items_count, facet: facet)
      end
    end
  end

end
