FactoryGirl.define do

  factory :facet, class: DataPlugins::Facet::Facet do
    title 'facet generated by factory'

    factory :facet_with_items do
      transient do
        facet_items_count 2
      end
      after(:create) do |facet, evaluator|
        create_list(:facet_item, evaluator.facet_items_count, facet: facet)
      end
    end
  end

end
